pipeline {
    agent any

    stages {

        stage('Clone Repo') {
            steps {
                checkout scm
            }
        }

        stage('Build JAR') {
            steps {
                dir('backend') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    sh 'docker build -t chat-backend:latest .'
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker rm -f chat-backend || true
                docker run -d \
                  --name chat-backend \
                  --network host \
                  -e KAFKA_BOOTSTRAP_SERVERS=127.0.0.1:9092 \
                  -e MONGODB_URI=mongodb://127.0.0.1:27017/chatapp \
                  chat-backend:latest
                '''
            }
        }
    }
}